// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	healthCheck: () => typedError<HealthStatus, AppError>(__TAURI_INVOKE("health_check")),
	getConfig: () => typedError<Config, AppError>(__TAURI_INVOKE("get_config")),
	setSteamApiKey: (key: string) => typedError<null, AppError>(__TAURI_INVOKE("set_steam_api_key", { key })),
	hasSteamApiKey: () => typedError<boolean, AppError>(__TAURI_INVOKE("has_steam_api_key")),
	clearSteamApiKey: () => typedError<null, AppError>(__TAURI_INVOKE("clear_steam_api_key")),
	setBackpackTfToken: (token: string) => typedError<null, AppError>(__TAURI_INVOKE("set_backpack_tf_token", { token })),
	hasBackpackTfToken: () => typedError<boolean, AppError>(__TAURI_INVOKE("has_backpack_tf_token")),
	clearBackpackTfToken: () => typedError<null, AppError>(__TAURI_INVOKE("clear_backpack_tf_token")),
	setDiscordWebhookUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("set_discord_webhook_url", { url })),
	hasDiscordWebhookUrl: () => typedError<boolean, AppError>(__TAURI_INVOKE("has_discord_webhook_url")),
	clearDiscordWebhookUrl: () => typedError<null, AppError>(__TAURI_INVOKE("clear_discord_webhook_url")),
	syncItemSchema: () => typedError<SchemaSyncSummary, AppError>(__TAURI_INVOKE("sync_item_schema")),
	/**
	 *  Runs the Steam OpenID login flow (system browser) and persists the
	 *  resulting SteamID64 to config on success.
	 */
	loginWithSteam: () => typedError<string, AppError>(__TAURI_INVOKE("login_with_steam")),
	getSteamId: () => typedError<string | null, AppError>(__TAURI_INVOKE("get_steam_id")),
	logoutSteam: () => typedError<null, AppError>(__TAURI_INVOKE("logout_steam")),
	syncInventory: () => typedError<InventorySyncSummary, AppError>(__TAURI_INVOKE("sync_inventory")),
	getInventory: () => typedError<BackpackItem[], AppError>(__TAURI_INVOKE("get_inventory")),
	setFavorite: (assetId: string, favorite: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_favorite", { assetId, favorite })),
	setPinned: (assetId: string, pinned: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_pinned", { assetId, pinned })),
	setFolder: (assetId: string, folder: string | null) => typedError<null, AppError>(__TAURI_INVOKE("set_folder", { assetId, folder })),
	setNote: (assetId: string, note: string | null) => typedError<null, AppError>(__TAURI_INVOKE("set_note", { assetId, note })),
	setCustomLabel: (assetId: string, label: string | null) => typedError<null, AppError>(__TAURI_INVOKE("set_custom_label", { assetId, label })),
	listTags: () => typedError<Tag[], AppError>(__TAURI_INVOKE("list_tags")),
	createTag: (name: string, color: string) => typedError<number, AppError>(__TAURI_INVOKE("create_tag", { name, color })),
	deleteTag: (tagId: number) => typedError<null, AppError>(__TAURI_INVOKE("delete_tag", { tagId })),
	addItemTag: (assetId: string, tagId: number) => typedError<null, AppError>(__TAURI_INVOKE("add_item_tag", { assetId, tagId })),
	removeItemTag: (assetId: string, tagId: number) => typedError<null, AppError>(__TAURI_INVOKE("remove_item_tag", { assetId, tagId })),
	syncPriceCatalog: () => typedError<PriceCatalogSyncSummary, AppError>(__TAURI_INVOKE("sync_price_catalog")),
	/**
	 *  Recent listing events observed via the live websocket feed (bounded
	 *  ring buffer) — a basic window into `MarketDataService` until the Live
	 *  Feed panel (Module 10) builds a proper UI around the same stream.
	 */
	getRecentListings: () => typedError<ListingEvent[], AppError>(__TAURI_INVOKE("get_recent_listings")),
	/**
	 *  Parses a backpack.tf classifieds URL, resolves the named item against
	 *  our schema-seeded `items` table, and computes current-moment analytics
	 *  (spread, liquidity, demand, estimated sale/quicksell, buyers/sellers
	 *  tables) from our own accumulated `market_listings`.
	 */
	analyzeClassifiedUrl: (url: string) => typedError<ItemAnalytics, AppError>(__TAURI_INVOKE("analyze_classified_url", { url })),
	/**
	 *  Daily OHLC bars for `url`'s resolved item (`price_daily`, Module 8's
	 *  History Recorder), for the Market Analyzer's price chart panel.
	 */
	getPriceHistory: (url: string) => typedError<PriceBar[], AppError>(__TAURI_INVOKE("get_price_history", { url })),
	/**
	 *  Fetches every active Steam trade offer the user has received and rates
	 *  each one (spread/liquidity/demand-based ★ rating, explanation,
	 *  counteroffer suggestion). Pull-based — the frontend polls this on an
	 *  interval rather than the backend pushing events (`docs/DESIGN.md`
	 *  Module 9 note in `services::trade_analysis_engine`).
	 */
	getActiveTrades: () => typedError<AnalyzedTradeOffer[], AppError>(__TAURI_INVOKE("get_active_trades")),
	/**
	 *  Creates an alert rule against the item a classifieds URL resolves to —
	 *  reuses `market_analyzer_service::resolve_item_id_from_url` (Module 7)
	 *  rather than requiring a separate item picker. Rejects up front (not
	 *  silently-never-fires) if `kind` needs a threshold and none was given.
	 */
	createAlertRule: (url: string, kind: string, threshold: number | null, channels: string[]) => typedError<number, AppError>(__TAURI_INVOKE("create_alert_rule", { url, kind, threshold, channels })),
	listAlertRules: () => typedError<AlertRuleView[], AppError>(__TAURI_INVOKE("list_alert_rules")),
	setAlertRuleEnabled: (ruleId: number, enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_alert_rule_enabled", { ruleId, enabled })),
	deleteAlertRule: (ruleId: number) => typedError<null, AppError>(__TAURI_INVOKE("delete_alert_rule", { ruleId })),
	listRecentAlertEvents: (limit: number) => typedError<AlertEventView[], AppError>(__TAURI_INVOKE("list_recent_alert_events", { limit })),
	ackAlertEvent: (eventId: number) => typedError<null, AppError>(__TAURI_INVOKE("ack_alert_event", { eventId })),
	/**
	 *  Scans every active item for flip opportunities (Module 11). Pull-based
	 *  — the frontend polls this on an interval, same shape as Module 9's
	 *  `get_active_trades`.
	 */
	getFlipOpportunities: (minRoiPct: number | null, minConfidence: number | null) => typedError<FlipOpportunityView[], AppError>(__TAURI_INVOKE("get_flip_opportunities", { minRoiPct, minConfidence })),
	/**
	 *  Adds the item a classifieds URL resolves to to the watchlist — reuses
	 *  `market_analyzer_service::resolve_item_id_from_url`, the same helper
	 *  Module 10's alert rules use, rather than a separate item picker.
	 */
	addToWatchlist: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("add_to_watchlist", { url })),
	removeFromWatchlist: (itemId: number | null) => typedError<null, AppError>(__TAURI_INVOKE("remove_from_watchlist", { itemId })),
	listWatchlist: () => typedError<WatchlistItemView[], AppError>(__TAURI_INVOKE("list_watchlist")),
};

/** Events */
export const events = {
	alertFired: makeEvent<AlertFired>("alert-fired"),
	inventoryChanged: makeEvent<InventoryChanged>("inventory-changed"),
	listingEventPushed: makeEvent<ListingEventPushed>("listing-event-pushed"),
};

/* Types */
export type AlertEventView = {
	id: number,
	rule_id: number,
	item_name: string,
	kind: string,
	message: string,
	fired_ts: number | null,
	acked: boolean,
};

export type AlertFired = {
	rule_id: number,
	item_name: string,
	kind: string,
	message: string,
	fired_ts: number | null,
	channels: string[],
};

export type AlertRuleView = {
	id: number,
	item_name: string,
	kind: string,
	threshold: number | null,
	channels: string[],
	enabled: boolean,
};

export type AnalyzedTradeOffer = {
	trade_offer_id: string,
	partner_steam_id: string,
	message: string,
	time_created: number | null,
	given_items: TradeItemView[],
	received_items: TradeItemView[],
	stars: number,
	given_total_ref: number | null,
	received_total_ref: number | null,
	net_ref: number | null,
	roi_pct: number | null,
	risk: string,
	explanation: string[],
	counteroffer_additional_ref: number | null,
	/**
	 *  Keys/metal breakdown of `counteroffer_additional_ref`, for a more
	 *  natural-reading suggested message — `None` alongside `None` when no
	 *  live key rate has been observed yet (`docs/DESIGN.md` §2: normalize
	 *  to ref internally, derive keys/metal for display only).
	 */
	counteroffer_additional_keys: number | null,
	counteroffer_additional_metal_ref: number | null,
};

/**
 *  Application-wide error type. Every IPC command returns `Result<T, AppError>`.
 * 
 *  Each variant maps to a stable `code` so the frontend can localize/branch on
 *  error kind without string-matching the message.
 */
export type AppError = { code: "config"; message: string } | { code: "database"; message: string } | { code: "keychain"; message: string } | { code: "network"; message: string } | { code: "invalid_input"; message: string } | { code: "internal"; message: string };

/**
 *  One backpack entry as the UI wants it: inventory/item data plus the
 *  user's own organization layer (`docs/DESIGN.md` §5).
 * 
 *  Field types are deliberately narrower than the DB's native `i64` —
 *  Specta forbids exporting 64-bit/platform-width integers to TypeScript to
 *  avoid silent precision loss, and everything here (row ids, craft
 *  numbers, paint RGB values) comfortably fits `i32`/`u32`/`u8` in practice.
 *  Timestamps use `f64`, which represents any realistic unix-seconds value
 *  exactly (53 bits of integer precision) without hitting that restriction.
 */
export type BackpackItem = {
	asset_id: string,
	item_id: number,
	name: string,
	quality: number,
	effect_id: number | null,
	killstreak_tier: number,
	australium: boolean,
	festivized: boolean,
	craftable: boolean,
	craft_number: number | null,
	paint_id: number | null,
	strange_count: number | null,
	tradable: boolean,
	marketable: boolean | null,
	acquired_ts: number | null,
	last_seen_ts: number | null,
	meta: ItemMeta,
	tags: Tag[],
};

/**
 *  User-editable application configuration, persisted as TOML in the OS
 *  config directory. Never holds secrets — those live in the OS keychain
 *  ([`crate::infra::keychain`]). `steam_id` is public/non-secret (see
 *  `docs/DESIGN.md` §2) so it's fine here, set after a successful OpenID
 *  login.
 */
export type Config = {
	log_level?: string,
	market_poll_interval_secs?: number,
	inventory_refresh_interval_secs?: number,
	steam_id?: string | null,
};

export type FlipOpportunityView = {
	item_name: string,
	buy_price_ref: number | null,
	sell_price_ref: number | null,
	quicksell_ref: number | null,
	expected_profit_ref: number | null,
	roi_pct: number | null,
	confidence: number | null,
	est_sale_time_hours: number | null,
	is_watched: boolean,
	is_high_volume: boolean,
	is_mover: boolean,
};

export type HealthStatus = {
	db_connected: boolean,
	config_dir: string,
	data_dir: string,
};

export type InventoryChanged = {
	steam_id: string,
	total: number,
};

export type InventorySyncSummary = {
	added: number,
	updated: number,
	unchanged: number,
	removed: number,
	total: number,
};

/**
 *  Current-moment analytics for one item (defindex(es) + quality + optional
 *  unusual effect), computed from `market_listings` — our own accumulated
 *  view of the live websocket feed (Module 5's snapshot-endpoint deviation
 *  means there's no on-demand REST source for this).
 * 
 *  `liquidity_score`/`demand_score` are computed with `volume_7d`,
 *  `buy_growth_pct`, and `sale_velocity_per_day` all at their neutral/zero
 *  defaults — we don't yet track completed trades over time, so these two
 *  scores lean entirely on current depth and listing freshness.
 * 
 *  The `trend_*` fields come from `price_daily` (Module 8's History
 *  Recorder) and are `None` until enough daily bars have accumulated for
 *  this exact item permutation.
 */
export type ItemAnalytics = {
	item_name: string,
	quality: number,
	effect_id: number | null,
	spread_abs_ref: number | null,
	spread_pct: number | null,
	liquidity_score: number | null,
	demand_score: number | null,
	estimated_sale_price_ref: number | null,
	estimated_quicksell_ref: number | null,
	buy_listings: ListingRow[],
	sell_listings: ListingRow[],
	trend_ma7_ref: number | null,
	trend_ma30_ref: number | null,
	trend_volatility_pct: number | null,
	trend_d1_pct: number | null,
	trend_d7_pct: number | null,
	trend_d30_pct: number | null,
	trend_d365_pct: number | null,
};

export type ItemMeta = {
	folder: string | null,
	pinned: boolean,
	favorite: boolean,
	note: string | null,
	custom_label: string | null,
};

export type ListingEvent = {
	listing_id: string,
	kind: ListingEventKind,
	defindex: number,
	quality: number,
	effect_id: number | null,
	killstreak_tier: number,
	australium: boolean,
	festivized: boolean,
	craftable: boolean,
	intent: string,
	steam_id: string,
	steam_name: string | null,
	/**
	 *  Total listing value already normalized to ref by backpack.tf
	 *  (`payload.value.raw`).
	 */
	value_ref: number | null,
};

/**
 *  A single listing update/removal from the live websocket feed. Kind is
 *  determined by `services::market_data_service` tracking which listing
 *  ids it's already seen — the wire protocol only distinguishes
 *  update-or-create (`listing-update`) from `listing-delete`.
 */
export type ListingEventKind = "new" | "updated" | "removed";

/**
 *  Tuple wrapper adding the `Event` derive at the services layer, so
 *  `infra/backpack_tf/models.rs::ListingEvent` itself stays Tauri-agnostic
 *  (nothing in `infra/` imports `tauri` today).
 */
export type ListingEventPushed = ListingEvent;

export type ListingRow = {
	listing_id: string,
	/**
	 *  Which defindex this row came from — worth surfacing when a name
	 *  resolves to several (class-specific reskins etc.), so the UI can
	 *  distinguish them if it wants to.
	 */
	defindex: number,
	steam_id: string,
	steam_name: string | null,
	price_ref: number | null,
	age_hours: number | null,
};

/**
 *  One daily OHLC bar (`price_daily`), for a charting panel. `ts` is a unix
 *  timestamp in seconds — Specta forbids exporting `i64` to TypeScript, and
 *  `f64` holds this magnitude exactly (well under 2^53).
 */
export type PriceBar = {
	ts: number | null,
	open_ref: number | null,
	high_ref: number | null,
	low_ref: number | null,
	close_ref: number | null,
	samples: number,
};

export type PriceCatalogSyncSummary = {
	items_cached: number,
	from_cache: boolean,
};

export type SchemaSyncSummary = {
	items_synced: number,
	particles_cached: number,
	qualities_cached: number,
	from_cache: boolean,
	/**
	 *  Total row count in `items` after this sync — can exceed
	 *  `items_synced` once inventory/market data starts adding permutations
	 *  (Strange, Unusual+effect, ...) beyond the schema's base entries.
	 */
	items_in_db: number,
};

export type Tag = {
	id: number,
	name: string,
	color: string,
};

export type TradeItemView = {
	name: string,
	/**
	 *  `None` when the item couldn't be resolved/priced at all — the
	 *  frontend should render this distinctly from a legitimately
	 *  zero-value item.
	 */
	estimated_ref: number | null,
};

export type WatchlistItemView = {
	item_id: number | null,
	item_name: string,
	added_ts: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

